### PR TITLE
BF: remove stray comma in dataset_description.json

### PR DESCRIPTION
**Pull request by adswa**
With this comma the file was not valid json. ping @loj

### CODE REVIEW

**Comment by loj** [comment]
Thanks for catching that! :-)

**Comment by adswa** [comment]
@loj @mih I plan to use this dataset for my OHBM open science room talk. Would it be possible to have this fix added and the BIDS branch fixed today or tomorrow? Let me know if I should do this, or if I can help if you don't have time.

**Comment by loj** [comment]
Hey @adswa I don't have permission to merge, so I can't add this fix or #4 

Are there additional adjustments you need made to the BIDS branch for your talk?

**Comment by adswa** [comment]
Oh sorry, I didn't know you didn't have permissions here. I'll merge this and #4 as well. Can you remind me where the bids branch was created? I propose merging both PRs into master, and rerun the BIDS conversion. Maybe we can have fmriprep have a go at one subject to check if it also works with #4 merged in, then update the bids branch.

**Comment by adswa** [comment]
> Are there additional adjustments you need made to the BIDS branch for your talk?

No, generally not. I tried with the fix of this comma, but we retry with the fixes in #4 applied once they are somewhere.

**Comment by mih** [comment]
> Hey @adswa I don't have permission to merge, so I can't add this fix or #4

@loj I sent you an invite to become maintainer just now.

**Comment by loj** [comment]
> No, generally not. I tried with the fix of this comma, but we retry with the fixes in #4 applied once they are somewhere.

Sounds good. Let me know if you come across other adjustments that need to be made.

**Pull request merged**
