### PR TITLE
add BIDS conversion script

### PR DESCRIPTION
**Pull request by loj**
I've created a BIDS conversion script based off of the [Common Derivatives BEP003](https://bids-specification.readthedocs.io/en/common-derivatives/05-derivatives/02-common-data-types.html).

As a non-neuroscientist, I had to do a bit of guessing on how to handle these files, and I'm especially unsure about the `space` label that I used. Any feedback or suggestions are welcome. @mih

### CODE REVIEW

**Comment by adswa** [comment]
I've looked into the ``space`` label. If I understand [the appendix of the common derivatives specs](https://bids-specification.readthedocs.io/en/common-derivatives/99-appendices/08-coordinate-systems.html#image-based-coordinate-systems) correctly, ``acpc`` is not among the allowed keywords. I *think* it should be `MNI152NLin6ASym`:

> A variation of MNI152NLin6Sym built by A. Janke that is released as the MNI template of FSL. Volumetric templates included with HCP-Pipelines correspond to this template too. See 10.1016/j.neuroimage.2012.01.024.

But I'm unsure myself.

**Comment by loj** [comment]
Thanks @adswa for the direction. :-)

I've updated the PR to use `MNI152NLin6ASym` as the `space` label.

I agree that `acpc` is not the correct keyword to use with the `space` label, and I am inclined to agree that `MNI152NLin6ASym` is the right thing use here, especially with the BIDS spec citing it as being used with the HCP Pipelines. Though there is also `fsLR`

> The fsLR is a dual template providing both volumetric and surface coordinates references. The volumetric template corresponds to MNI152NLin6Asym. Surface templates are given at several sampling densities: 164k (used by HCP pipelines for 3T and 7T anatomical analysis), 59k (used by HCP pipelines for 7T MRI bold and DWI analysis), 32k (used by HCP pipelines for 3T MRI bold and DWI analysis), or 4k (used by HCP pipelines for MEG analysis) fsaverage_LR surface reconstructed from the T1w image.

I did some digging in this [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3720813/) on the HCP preprocessing pipelines, which specifically talks about the PreFreeSurfer pipeline aligning the coordinate space axes to those of the MNI template. I think this section outlines it, but due to my lack of vocabulary in this area, I'm not completely sure whether this is volumetric only (though it sure seems that way).

> The main goals of the first structural pipeline, PreFreeSurfer, are to produce an undistorted “native” structural volume space for each subject, align the T1w and T2w images, perform a B1 (bias field) correction, and register the subject’s native structural volume space to MNI space. Thus, there are two volume spaces in HCP data (overview in Figure 8): 1) The subject’s undistorted native volume space (rigidly “aligned” to the axes of MNI space), which is where volumes and areas of structures should be measured and where tractography should be performed, as this space is the best approximation of the subject’s physical brain. 2) Standard MNI space is useful for comparisons across subjects and studies, particularly of subcortical data, which is more accurately aligned by nonlinear volume registration than cortical data is.

**Comment by adswa** [comment]
The more I read into this, the more confused I am. In the paragraphs on structural pipelines, the paper you cited continues:
> The outputs of the PreFreeSurfer pipeline are organized into a folder (by default called T1w) that contains the native volume space images and a second folder (by default called MNINonLinear) that contains the MNI space images. 

Given that the 5 files all come out of the T1w folder, this seems to suggest that the space of these files is the subjects native space...

**Comment by adswa** [comment]
If this is the case, we might want to not add a `space` keyword at all to these T1 images. From the [specs](https://bids-specification.readthedocs.io/en/common-derivatives/05-derivatives/02-common-data-types.html):
> The `space` keyword is recomended to distinguish files with different underlying coordinate systems or registered to different reference maps.

File names would then rely on the ``desc`` keyword only...
> Note that even though space and desc are optional at least one of them MUST be defined to avoid name conflict with the raw file.

**Comment by loj** [comment]
I read this as well and wondered if native space is what we want. But, since `native` wasn't listed among the allowed keywords for the `space` label and the sentence in the paper stating:

> The subject’s undistorted native volume space (rigidly “aligned” to the axes of MNI space)...

I was uncertain if `native` was correct.

@adswa wrote:
> If this is the case, we might want to not add a space keyword at all to these T1 images.

I think this is a good suggestion. I'll remove the `space` label and just use the `desc` label for now. 

Thanks for your input. :-)

**Comment by mih** [comment]
Awesome, thx much! This works for me. I will push a minor change that should make it easier to run this script multiple times (e.g. in case of an update and a required re-BIDSification)..

**Comment by mih** [comment]
Thanks to @loj and @adswa the following is now possible:

`datalad clone ria+http://store.datalad.org#~hcp-structural-preprocessed@bids`

**Comment by dbkeator** [comment]
FYI, I tried the clone command above and received an error "RIA URI does not contain a valid dataset ID".  Figured I'd give it a try and see if I could use it as a test case for augmenting my bids -> nidm converter to handle derivatives.

**Comment by yarikoptic** [comment]
you should use the 0.13.0rc1 release candidate of datalad or master branch directly,

**Pull request merged**
